### PR TITLE
Add stack.yaml

### PR DESCRIPTION
**Pull request by brandon-leapyear**
Supercedes #15, just adds stack.yaml, doesn't convert cabal file into hpack

### CODE REVIEW

**Comment by newhoggy** [comment]
It should be possible to just `stack init` for those people who want to develop with stack.

There should be CI for `stack` however, and that will be added in https://github.com/haskell-works/tasty-discover/pull/21

**Comment by brandon-leapyear** [comment]
It's actually not, because stack will try to find a resolver matching all
the constraints, and currently, the cabal file lists a lower bound for
packages that are not yet on Stackage (see extra-deps).

Regardless, what's the harm in just committing the file?

**Comment by newhoggy** [comment]
I've bumped down the version of the dependency and it should be an issue anymore.

Regarding the stack trying to find a resolve, the CI will explicitly choose a resolver, so stack should be searching for a resolver in that case.

**Comment by newhoggy** [comment]
This now works:

```
$ stack init
Looking for .cabal or package.yaml files to use to init the project.
Using cabal packages:
- ./

Selecting the best among 21 snapshots...

* Matches https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/19/7.yaml

Selected resolver: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/19/7.yaml
Initialising configuration using resolver: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/19/7.yaml
Total number of user packages considered: 1
Writing configuration to file: stack.yaml
All done.
```

**Comment by brandon-leapyear** [comment]
Should there be a test in CI for a plain stack init? I noticed the current
CI job specifies hardcoded resolvers.

**Comment by newhoggy** [comment]
I think if `stack init` works for any lts, then it should work without an lts.

I'll be happy to add `stack init` without a resolver if we bump into a case where this isn't true.

**Comment by brandon-leapyear** [comment]
Sounds good. Thanks!

**Pull request closed without merging**
